version: "3.2"
services:
  app:
    build: .
    container_name: app
    image: app
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
        - .env
    volumes:
      - ./project:/project
    ports:
      - "8000:8000"
